import {
  birthDate,
  firstNode,
  fourthNode,
  secondNode,
  thirdNode,
  age,
  country,
  district,
  specialists,
} from './data'

export const nodeElements = [
  {
    id: '1',
    type: 'start',
    data: { label: 'An input node' },
    position: { x: 300, y: -90 },
  },
  {
    id: '2',
    type: 'question',
    data: firstNode,
    position: { x: 33, y: 50 },
  },
  {
    id: '3',
    type: 'question',
    data: secondNode,
    position: { x: 700, y: 270 },
  },
  {
    id: '4',
    type: 'question',
    data: thirdNode,
    position: { x: 700, y: 560 },
  },
  {
    id: '5',
    type: 'question',
    data: fourthNode,
    position: { x: 1483, y: 760 },
  },
  {
    id: '6',
    type: 'question',
    data: birthDate,
    position: { x: 1405, y: 990 },
  },
  {
    id: '7',
    type: 'question',
    data: age,
    position: { x: 1400, y: 1240 },
  },
  {
    id: '8',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 1340, y: 830 },
  },
  {
    id: '9',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 2080, y: 1240 },
  },
  {
    id: '10',
    type: 'question',
    data: country,
    position: { x: 1940, y: 1660 },
  },
  {
    id: '11',
    type: 'question',
    data: district,
    position: { x: 2580, y: 1920 },
  },
  {
    id: '12',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 2580, y: 2400 },
  },
  {
    id: '13',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 3200, y: 2360 },
  },
  {
    id: '14',
    type: 'question',
    data: specialists,
    position: { x: 3300, y: 2280 },
  },
  {
    id: '15',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 3940, y: 2800 },
  },
  // edges
  {
    id: 'e1-2',
    source: '1',
    target: '2',
  },
  {
    id: 'e2b-4',
    source: '2',
    target: '3',
    sourceHandle: '1',
  },
  {
    id: 'e3-4',
    source: '3',
    target: '4',
  },
  {
    id: 'e4-5',
    source: '4',
    target: '5',
    sourceHandle: '0',
  },
  {
    id: 'e5-6',
    source: '5',
    target: '6',
  },
  {
    id: 'e6-7',
    source: '6',
    target: '7',
  },
  {
    id: 'e4a-8',
    source: '4',
    target: '8',
    sourceHandle: '1',
  },
  {
    id: 'e7a-9',
    source: '7',
    target: '9',
    sourceHandle: '0',
  },
  {
    id: 'e7b-10',
    source: '7',
    target: '10',
    sourceHandle: '1',
  },
  {
    id: 'e7c-10',
    source: '7',
    target: '10',
    sourceHandle: '2',
  },
  {
    id: 'e7d-10',
    source: '7',
    target: '10',
    sourceHandle: '3',
  },
  {
    id: 'e7e-10',
    source: '7',
    target: '10',
    sourceHandle: '4',
  },
  {
    id: 'e10a-11',
    source: '10',
    target: '11',
    sourceHandle: '0',
  },
  {
    id: 'e10f-12',
    source: '10',
    target: '12',
    sourceHandle: '10',
  },
  {
    id: 'e11f-13',
    source: '11',
    target: '13',
    sourceHandle: '4',
  },
  {
    id: 'e11a-14',
    source: '11',
    target: '14',
    sourceHandle: '0',
  },
  {
    id: 'e11b-14',
    source: '11',
    target: '14',
    sourceHandle: '1',
  },
  {
    id: 'e11c-14',
    source: '11',
    target: '14',
    sourceHandle: '2',
  },
  {
    id: 'e11d-14',
    source: '11',
    target: '14',
    sourceHandle: '3',
  },
  {
    id: 'e14f-15',
    source: '14',
    target: '15',
    sourceHandle: '5',
  },
]
