import {
  birthDate,
  firstNode,
  fourthNode,
  secondNode,
  thirdNode,
  age,
  country,
  district,
  specialists,
  permanentResidence,
  typeOfResidence,
  howManyTVs,
  firstCondition,
  typeOfAntenna,
  secondCondition,
} from './data'

export const nodeElements = [
  {
    id: '1',
    type: 'start',
    data: { label: 'An input node' },
    position: { x: 300, y: -250 },
  },
  {
    id: '2',
    type: 'question',
    data: firstNode,
    position: { x: 33, y: -50 },
  },
  {
    id: '3',
    type: 'question',
    data: secondNode,
    position: { x: 700, y: 250 },
  },
  {
    id: '4',
    type: 'question',
    data: thirdNode,
    position: { x: 700, y: 560 },
  },
  {
    id: '5',
    type: 'question',
    data: fourthNode,
    position: { x: 1483, y: 760 },
  },
  {
    id: '6',
    type: 'question',
    data: birthDate,
    position: { x: 1405, y: 990 },
  },
  {
    id: '7',
    type: 'question',
    data: age,
    position: { x: 1400, y: 1220 },
  },
  {
    id: '8',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 1340, y: 830 },
  },
  {
    id: '9',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 2080, y: 1240 },
  },
  {
    id: '10',
    type: 'question',
    data: country,
    position: { x: 1940, y: 1660 },
  },
  {
    id: '11',
    type: 'question',
    data: district,
    position: { x: 2660, y: 2040 },
  },
  {
    id: '12',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 2580, y: 2400 },
  },
  {
    id: '13',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 3320, y: 2460 },
  },
  {
    id: '14',
    type: 'question',
    data: specialists,
    position: { x: 3160, y: 2640 },
  },
  {
    id: '15',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 4180, y: 3080 },
  },
  {
    id: '16',
    type: 'question',
    data: permanentResidence,
    position: { x: 3780, y: 3180 },
  },
  {
    id: '17',
    type: 'question',
    data: typeOfResidence,
    position: { x: 4520, y: 3480 },
  },
  {
    id: '18',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 4420, y: 3480 },
  },
  {
    id: '19',
    type: 'question',
    data: howManyTVs,
    position: { x: 5260, y: 3840 },
  },
  {
    id: '20',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 5160, y: 3840 },
  },
  {
    id: '21',
    type: 'condition',
    data: firstCondition,
    position: { x: 6020, y: 3520 },
  },
  {
    id: '22',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 6085, y: 3800 },
  },
  {
    id: '23',
    type: 'question',
    data: typeOfAntenna,
    position: { x: 6000, y: 4340 },
  },
  {
    id: '24',
    type: 'finish',
    data: { label: 'Finish' },
    position: { x: 5885, y: 4400 },
  },
  {
    id: '25',
    type: 'condition',
    data: secondCondition,
    position: { x: 6840, y: 4400 },
  },
  // edges
  {
    id: 'e1-2',
    source: '1',
    target: '2',
  },
  {
    id: 'e2b-4',
    source: '2',
    target: '3',
    sourceHandle: '1',
  },
  {
    id: 'e3-4',
    source: '3',
    target: '4',
  },
  {
    id: 'e4-5',
    source: '4',
    target: '5',
    sourceHandle: '0',
  },
  {
    id: 'e5-6',
    source: '5',
    target: '6',
  },
  {
    id: 'e6-7',
    source: '6',
    target: '7',
  },
  {
    id: 'e4a-8',
    source: '4',
    target: '8',
    sourceHandle: '1',
  },
  {
    id: 'e7a-9',
    source: '7',
    target: '9',
    sourceHandle: '0',
  },
  {
    id: 'e7b-10',
    source: '7',
    target: '10',
    sourceHandle: '6',
  },
  {
    id: 'e10a-11',
    source: '10',
    target: '11',
    sourceHandle: '0',
  },
  {
    id: 'e10f-12',
    source: '10',
    target: '12',
    sourceHandle: '10',
  },
  {
    id: 'e11f-13',
    source: '11',
    target: '13',
    sourceHandle: '4',
  },
  {
    id: 'e11a-14',
    source: '11',
    target: '14',
    sourceHandle: '8',
  },
  {
    id: 'e14a-15',
    source: '14',
    target: '15',
    sourceHandle: '9',
  },
  {
    id: 'e14f-16',
    source: '14',
    target: '16',
    sourceHandle: '5',
  },
  {
    id: 'e10-14',
    source: '10',
    target: '14',
  },
  {
    id: 'e16a-17',
    source: '16',
    target: '17',
    sourceHandle: '0',
  },
  {
    id: 'e16b-18',
    source: '16',
    target: '18',
    sourceHandle: '1',
  },
  {
    id: 'e17a-19',
    source: '17',
    target: '19',
    sourceHandle: '11',
  },
  {
    id: 'e17d-20',
    source: '17',
    target: '20',
    sourceHandle: '3',
  },
  {
    id: 'e19a-21',
    source: '19',
    target: '21',
    sourceHandle: '0',
    targetHandle: '1',
  },
  {
    id: 'e10b-21',
    source: '10',
    target: '21',
    sourceHandle: '1',
    targetHandle: '0',
  },
  {
    id: 'e21-22',
    source: '21',
    target: '22',
  },
  {
    id: 'e19e-24',
    source: '19',
    target: '24',
    sourceHandle: '5',
  },
  {
    id: 'e19c-23',
    source: '19',
    target: '23',
    sourceHandle: '12',
  },
  {
    id: 'e23a-25',
    source: '23',
    target: '25',
    sourceHandle: '14',
  },
]
